name             'cligem'
maintainer       'James FitzGibbon'
maintainer_email 'james@nadt.net'
license          'All rights reserved'
description      'LWRP to set up a gem that includes CLI elements using rbenv and bundler'
version          '0.1.3'
depends          'rbenv', '~> 0.7'
depends          'ruby_build', '~> 0.8'
conflicts        'rbenv', '>= 1'
