name             'cligem'
maintainer       'James FitzGibbon'
maintainer_email 'james@nadt.net'
license          'All rights reserved'
description      'LWRP to set up a gem that includes CLI elements using rbenv and bundler'
version          '0.1.0'
depends          'rbenv'
